### ISSUE TITLE
"Add Bear" Button : Change font family to Roboto from Times New Roman

### ISSUE THREAD

**Issue by hemangsk** [coala/landing-frontend#270]
From coala Online : 
<img width="226" alt="screen shot 2018-04-09 at 4 40 06 pm" src="https://user-images.githubusercontent.com/13018570/38494791-ccea34de-3c14-11e8-922d-63cd383957a0.png">

**Comment by jayvdb** [comment]
Hi, I'm [GitMate.io](https://gitmate.io)!

It seems you've just enabled the issue triaging. I'm just scraping all issues from your repository and will give you some more information about this in a few minutes or so.

Because of the rate limit we can't scrape all information (including all comments and authors) right now - our system is already set up to scrape this in the next days over which the predictions will become more precise every day.

If you want me to use a different account for triaging your issues, simply create one and log in with it.

**Sit tight!**

**Comment by hemangsk** [comment]
Also I think it makes sense to centre align this button to improve its visibility

**Comment by hrithik-jha** [comment]
Hi, I'd like to work on this. Where is the button exactly?

**Comment by vaibhav9619** [comment]
please assign me this issue

**Comment by manangoel99** [comment]
Can I work on this?

**Comment by jayvdb** [comment]
Can you find the file which needs to be modified?
If you cant find the right file, this task isnt suitable for you.
Reply here thanks.

**Comment by jayvdb** [comment]
The button does not need to be added.  It is already in the page.  The font needs to change.

btw, you can see it in action at https://coala.io/#/coalaonline
